var first_name = "Ranbir";
var last_name = "Kapoor";
var a = 10;
var b = 5;
full_name = first_name.concat(last_name);
console.log(full_name);
add = a + b;
console.log(add);
subtract = a - b;
console.log(subtract);